//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSite.Diagrams
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public Answers()
        {
            this.AnswerQuestions = new HashSet<AnswerQuestions>();
            this.LearnerAnswers = new HashSet<LearnerAnswers>();
        }
    
        public int AnswerID { get; set; }
        public string AnswerText { get; set; }
    
        public virtual ICollection<AnswerQuestions> AnswerQuestions { get; set; }
        public virtual ICollection<LearnerAnswers> LearnerAnswers { get; set; }
    }
}
