//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSite.Diagrams
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentityRoles
    {
        public IdentityRoles()
        {
            this.IdentityUserRoles = new HashSet<IdentityUserRoles>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<IdentityUserRoles> IdentityUserRoles { get; set; }
    }
}
