//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSite.Diagrams
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentityUserRoles
    {
        public string RoleId { get; set; }
        public string UserId { get; set; }
        public string Role_Id { get; set; }
    
        public virtual IdentityRoles IdentityRoles { get; set; }
        public virtual IdentityUsers IdentityUsers { get; set; }
    }
}
