//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSite.Diagrams
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institutions
    {
        public Institutions()
        {
            this.Groups = new HashSet<Groups>();
        }
    
        public int InstitutionID { get; set; }
        public string InstitutionName { get; set; }
        public string InstitutionPlace { get; set; }
        public string InstitutionAddress { get; set; }
    
        public virtual ICollection<Groups> Groups { get; set; }
    }
}
