//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSite.Diagrams
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnswerQuestions> AnswerQuestions { get; set; }
        public virtual DbSet<Answers> Answers { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<IdentityRoles> IdentityRoles { get; set; }
        public virtual DbSet<IdentityUserClaims> IdentityUserClaims { get; set; }
        public virtual DbSet<IdentityUserLogins> IdentityUserLogins { get; set; }
        public virtual DbSet<IdentityUserRoles> IdentityUserRoles { get; set; }
        public virtual DbSet<IdentityUsers> IdentityUsers { get; set; }
        public virtual DbSet<Institutions> Institutions { get; set; }
        public virtual DbSet<LearnerAnswers> LearnerAnswers { get; set; }
        public virtual DbSet<QuestionAreas> QuestionAreas { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
        public virtual DbSet<QuestionTypes> QuestionTypes { get; set; }
        public virtual DbSet<Tests> Tests { get; set; }
    }
}
