//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSite.Diagrams
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public Questions()
        {
            this.AnswerQuestions = new HashSet<AnswerQuestions>();
            this.LearnerAnswers = new HashSet<LearnerAnswers>();
            this.Tests = new HashSet<Tests>();
        }
    
        public int QuestionID { get; set; }
        public int QuestionAreaID { get; set; }
        public int QuestionTypeID { get; set; }
        public Nullable<int> Complexity { get; set; }
        public string Text { get; set; }
        public Nullable<int> SolvingTime { get; set; }
        public Nullable<int> Points { get; set; }
        public string ImagePath { get; set; }
    
        public virtual ICollection<AnswerQuestions> AnswerQuestions { get; set; }
        public virtual ICollection<LearnerAnswers> LearnerAnswers { get; set; }
        public virtual QuestionAreas QuestionAreas { get; set; }
        public virtual QuestionTypes QuestionTypes { get; set; }
        public virtual ICollection<Tests> Tests { get; set; }
    }
}
