//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSite.Diagrams
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionAreas
    {
        public QuestionAreas()
        {
            this.Questions = new HashSet<Questions>();
        }
    
        public int QuestionAreaID { get; set; }
        public string QuestionAreaName { get; set; }
        public double Possibility { get; set; }
        public int ParentQuestionAreaID { get; set; }
    
        public virtual ICollection<Questions> Questions { get; set; }
    }
}
