//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSite.Diagrams
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tests
    {
        public Tests()
        {
            this.Questions = new HashSet<Questions>();
        }
    
        public int TestID { get; set; }
        public string TestName { get; set; }
        public Nullable<int> SolvingTime { get; set; }
    
        public virtual ICollection<Questions> Questions { get; set; }
    }
}
